# -------------------------------------------------------------------------
#	Aide
# -------------------------------------------------------------------------

help : 
	@echo ""
	@echo "                       Implantation de Lista"
	@echo "                       ---------------------"
	@echo ""
	@echo "Pour connaitre les versions des out:ils a votre disposition, utilisez:"
	@echo "   - g++ --version"
	@echo "   - flex --version"
	@echo "   - bison --version"
	@echo "   - make --version"
	@echo ""
	@echo "Pour construire ListaPDR et ListaFB:"
	@echo "     make"
	@echo ""
	@echo "Pour construire FonctionsImbriquees:"
	@echo "     make FonctionsImbriquees"
	@echo ""
	@echo "Pour tout construire, y-compris les versions incompletes des compilateurs:"
	@echo "     make all"
	@echo ""
	@echo "Pour construire un seul element, par exemple:"
	@echo "     make ListaSemFB"
	@echo ""
	@echo "Pour construire tous les executable *P et *PDR:"
	@echo "     make pdr"
	@echo ""
	@echo "Pour construire tous les executable *F et *FB:"
	@echo "     make fb"
	@echo ""
	@echo "Pour construire la documentation avec Doxygen dans le dossier .."
	@echo "     make doc"
	@echo ""
	@echo "Pour continuer la construction en cas d'erreur sur un element:"
	@echo "     make -i [...]"
	@echo ""
	@echo "Pour voir l'effet des dependances:"
	@echo "     make -d [...]"
	@echo ""
	@echo "Pour faire le menage:"
	@echo "     make noobjs     : supprime les codes objets g++ et les executables"
	@echo "                       A faire avant de porter sur une autre architecture"
	@echo "     make notemps    : supprime les fichiers intermediaires utilises par g++"
	@echo "     make nofb       : supprime les fichiers crees par Flex et Bison"
	@echo "     make nobinaries : supprime les fichiers de code objet Pilum"
	@echo "     make clean      : tous les precedents d'un coup"
	@echo ""
	@echo "*** Pour tester les implantations de Lista de base construites dans le dossier courant: ***"
	@echo "     make test       (fait compiler un exemple et executer le code objet)"
	@echo ""
	@echo "*** Pour tester vos extensions de Lista lors de l'examen oral: ***"
	@echo "     make examen     (fait compiler votre exemple et executer le code objet, a vous de jouer!)"
	@echo ""
	@echo "Pour installer/desinstaller les executables dans $(DOSSIER_D_INSTALLATION):"
	@echo "     make install    (fait en general par 'root')"
	@echo "     make uninstall  (fait en general par 'root')"
	@echo ""
	@echo "Pour tout savoir sur 'make':"
	@echo "     make --help"
	@echo "     man make"
	@echo ""
	@echo ""
	@echo "--> Pour:"
	@echo "    tout savoir sur la construction de Lista:         make help"
	@echo ""
	@echo "    construire et tester la base minimale:            make test"
	@echo "    construire et tester la version de l'examen:      make examen"
	@echo ""
	@echo "    construire FonctionsImbriquees:                   make FonctionsImbriquees"
	@echo ""
	@echo "    execution directe de '99 bouteilles de biere':    make 99d"
	@echo "    execution de '99 bouteilles de biere' par Pilum:  make 99p"
	@echo ""
	@echo "    construire tous les executables:                  make all"
	@echo ""
	@echo "    construire la documentation:                      make doc"
	@echo ""
	@echo "    supprimer tout ce qui a ete construit:            make clean"
	@echo ""
